### ISSUE TITLE
Create a .gitignore file and remove those files

### ISSUE THREAD

**Issue by bsoyka** [bsoyka/magic-py-ball#14]
This should be a basic `.gitignore` file.  You can just copy the example [here](
https://github.com/github/gitignore/blob/master/Python.gitignore).
Then, remove any files and folders included in the `.gitignore` from this repository, for example, the `dist/` directory.

**Comment by focux** [comment]
I will work on it. Do you want the same .gitignore of that example?

**Comment by bsoyka** [comment]
Sure, @focux!
