### ISSUE TITLE
Allow programmatic question input

### ISSUE THREAD

**Issue by bsoyka** [bsoyka/magic-py-ball#3]
Make a parameter in the main function, maybe change the function’s name.

**Comment by mbuccat** [comment]
Hi @bsoyka , I'd like to work on this

**Comment by bsoyka** [comment]
Okay, @mbuccat, sounds good!  Just curious, how did you hear about this repo?  I’ve been getting visitors and I’m wondering where they’re from.

**Comment by mbuccat** [comment]
I looked up issues labeled "good first issue" (I'm trying to familiarize myself with git and also participate in [Hacktoberfest](https://hacktoberfest.digitalocean.com)).  Maybe your other visitors are doing the same!

**Comment by bsoyka** [comment]
Okay, thanks for letting me know!  I’m actually participating in Hacktoberfest myself.  Let me know if you need anything with this issue.
